"""Persist and list scraped jobs in the Supabase `jobs` table."""
import logging
from typing import Optional

logger = logging.getLogger("api.jobs_repository")

TABLE = "jobs"


class JobsRepository:
    """Upserts scraped jobs (deduped by url) and lists them."""

    def __init__(self, client, table: str = TABLE) -> None:
        self.client = client
        self.table = table

    def upsert(self, job: dict) -> None:
        company = job.get("company")
        if not company:
            logger.warning("Skipping job with no company: %s", job.get("job_url"))
            return
        url = job.get("job_url")
        row = {
            "role": job.get("title"),
            "company": company,
            "url": url,
            "location": job.get("location"),
            "description": job.get("description"),
        }
        # Dedupe by url in application code: the `jobs` table has no unique
        # constraint on `url`, so PostgREST's on_conflict upsert can't be used
        # (Postgres error 42P10). Update an existing row with the same url,
        # otherwise insert a new one (id is auto-generated by the DB).
        table = self.client.table(self.table)
        if url:
            existing = table.select("id").eq("url", url).limit(1).execute()
            if existing.data:
                table.update(row).eq("url", url).execute()
                return
        table.insert(row).execute()

    def list_jobs(self, limit: int = 100) -> list:
        resp = (
            self.client.table(self.table)
            .select("id,company,role,url,location,description,created_at")
            .order("created_at", desc=True)
            .limit(limit)
            .execute()
        )
        return resp.data or []


def build_jobs_repository(supabase_url, service_key) -> Optional[JobsRepository]:
    """Build a JobsRepository from Supabase creds, or None if unavailable."""
    if not (supabase_url and service_key):
        return None
    try:
        from supabase import create_client

        return JobsRepository(create_client(supabase_url, service_key))
    except Exception:
        logger.exception("Jobs repository unavailable; job persistence disabled")
        return None
